// BCA website audit: content/asset inventory + axe-core accessibility scan.
//
// Crawls a site (same-origin BFS), and for every page extracts a structured
// inventory (headings, images+alt, links, embeds, PDFs, forms) and runs an
// axe-core WCAG 2.1 A/AA scan. Writes JSON + Markdown reports under audit/reports.
//
// Usage:
//   node audit.mjs <baseUrl> [--max N] [--no-proxy] [--out DIR] [--wait MS]
//
// The site is Wix (JS-rendered), so pages are loaded with waitUntil:networkidle
// plus a settle delay before extraction. In this managed environment outbound
// HTTPS goes through HTTPS_PROXY; the script auto-uses it unless --no-proxy.
//
// Examples:
//   node audit.mjs https://www.bonitacenterforthearts.com --max 40
//   node audit.mjs file:///abs/path/fixtures/index.html --no-proxy --max 10

import { chromium } from 'playwright';
import axeSource from 'axe-core';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const args = process.argv.slice(2);
if (!args[0] || args[0].startsWith('--')) {
  console.error('Usage: node audit.mjs <baseUrl> [--max N] [--no-proxy] [--out DIR] [--wait MS]');
  process.exit(1);
}
const BASE = args[0];
const getFlag = (name, def) => {
  const i = args.indexOf(name);
  return i === -1 ? def : args[i + 1];
};
const MAX_PAGES = parseInt(getFlag('--max', '40'), 10);
const SETTLE_MS = parseInt(getFlag('--wait', '1500'), 10);
const USE_PROXY = !args.includes('--no-proxy') && !!process.env.HTTPS_PROXY;
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(getFlag('--out', path.join(scriptDir, '..', 'audit', 'reports')));

// ---- URL helpers -----------------------------------------------------------
const isHttp = (u) => /^https?:/i.test(u);
function normalize(u) {
  try {
    const url = new URL(u);
    url.hash = '';
    // Drop trailing slash (except root) for dedupe stability.
    if (url.pathname.length > 1 && url.pathname.endsWith('/')) {
      url.pathname = url.pathname.replace(/\/+$/, '');
    }
    return url.toString();
  } catch {
    return null;
  }
}
let baseOrigin = null;
try { baseOrigin = new URL(BASE).origin; } catch { /* file:// etc */ }
const sameOrigin = (u) => {
  try { return new URL(u).origin === baseOrigin; } catch { return false; }
};

// ---- alt-text heuristic ----------------------------------------------------
// Flags alt text that is almost certainly auto-generated / non-descriptive
// (Wix default behavior often emits the raw filename).
function altLooksAutogenerated(alt) {
  if (alt == null) return false;
  const a = alt.trim();
  if (!a) return false;
  const patterns = [
    /\.(jpe?g|png|gif|webp|svg|bmp|tiff?)$/i, // ends in an image extension
    /^(img|dsc|dscn|pxl|photo|image|screen ?shot|screenshot|unnamed|untitled)[-_ ]?\d*/i,
    /^[0-9a-f]{8}[-_]?[0-9a-f]{4}/i,          // GUID-ish
    /^[0-9a-f]{16,}$/i,                       // long hex blob
    /%[0-9a-f]{2}/i,                          // url-encoded chars
    /_\d{3,}x\d{3,}/i,                        // dimensions baked in (Wix "..._1024x768")
    /~mv2/i,                                  // Wix media token
  ];
  return patterns.some((re) => re.test(a));
}

// ---- per-page extraction (runs in browser) ---------------------------------
async function extractInventory(page) {
  return page.evaluate(() => {
    const abs = (u) => { try { return new URL(u, document.baseURI).toString(); } catch { return u; } };
    const headings = [...document.querySelectorAll('h1,h2,h3,h4,h5,h6')].map((h) => ({
      level: Number(h.tagName[1]),
      text: (h.textContent || '').trim().replace(/\s+/g, ' ').slice(0, 160),
    }));
    const images = [...document.querySelectorAll('img')].map((img) => ({
      src: abs(img.getAttribute('src') || img.getAttribute('data-src') || ''),
      alt: img.hasAttribute('alt') ? img.getAttribute('alt') : null,
      hasAltAttr: img.hasAttribute('alt'),
      role: img.getAttribute('role'),
      w: img.naturalWidth || null,
      h: img.naturalHeight || null,
    }));
    const links = [...document.querySelectorAll('a[href]')].map((a) => ({
      href: abs(a.getAttribute('href')),
      text: (a.textContent || '').trim().replace(/\s+/g, ' ').slice(0, 120),
      ariaLabel: a.getAttribute('aria-label'),
    }));
    const iframes = [...document.querySelectorAll('iframe')].map((f) => ({
      src: abs(f.getAttribute('src') || ''),
      title: f.getAttribute('title'),
    }));
    const forms = [...document.querySelectorAll('form')].map((form) => {
      const controls = [...form.querySelectorAll('input,select,textarea')].map((c) => {
        const id = c.getAttribute('id');
        let labelled = false;
        if (c.getAttribute('aria-label') || c.getAttribute('aria-labelledby')) labelled = true;
        if (id && document.querySelector(`label[for="${CSS.escape(id)}"]`)) labelled = true;
        if (c.closest('label')) labelled = true;
        if (c.getAttribute('type') === 'hidden' || c.getAttribute('type') === 'submit') labelled = true;
        return { tag: c.tagName.toLowerCase(), type: c.getAttribute('type'), name: c.getAttribute('name'), id, labelled };
      });
      return { action: abs(form.getAttribute('action') || ''), controls };
    });
    return {
      title: document.title,
      lang: document.documentElement.getAttribute('lang'),
      metaDescription: (document.querySelector('meta[name="description"]') || {}).content || null,
      headings, images, links, iframes, forms,
    };
  });
}

// ---- axe-core scan ---------------------------------------------------------
async function runAxe(page) {
  await page.addScriptTag({ content: axeSource.source });
  return page.evaluate(async () => {
    // eslint-disable-next-line no-undef
    const results = await axe.run(document, {
      runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'best-practice'] },
      resultTypes: ['violations'],
    });
    return results.violations.map((v) => ({
      id: v.id, impact: v.impact, help: v.help, helpUrl: v.helpUrl,
      tags: v.tags,
      nodes: v.nodes.slice(0, 8).map((n) => ({ target: n.target, html: (n.html || '').slice(0, 240) })),
      count: v.nodes.length,
    }));
  });
}

// ---- crawl -----------------------------------------------------------------
async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const launchOpts = USE_PROXY ? { proxy: { server: process.env.HTTPS_PROXY } } : {};
  console.log(`[audit] base=${BASE} maxPages=${MAX_PAGES} proxy=${USE_PROXY ? process.env.HTTPS_PROXY : 'off'}`);

  const queue = [normalize(BASE)].filter(Boolean);
  const seen = new Set(queue);
  const pages = [];
  const errors = [];
  let browser = null;

  // The crawl is wrapped so that any unexpected failure (browser launch/close,
  // newPage, an internal Playwright error) still flushes the pages gathered so
  // far — a mid-crawl crash should degrade to a partial report, not zero output.
  try {
    browser = await chromium.launch(launchOpts);
    const context = await browser.newContext({ userAgent: 'BCA-Audit-Bot (accessibility+content inventory)' });

    while (queue.length && pages.length < MAX_PAGES) {
      const url = queue.shift();
      let page = null;
      try {
        page = await context.newPage();
        const resp = await page.goto(url, { waitUntil: 'networkidle', timeout: 60000 });
        await page.waitForTimeout(SETTLE_MS);
        const status = resp ? resp.status() : null;
        const inv = await extractInventory(page);
        let violations = [];
        try { violations = await runAxe(page); } catch (e) { errors.push({ url, phase: 'axe', error: String(e).slice(0, 200) }); }
        pages.push({ url, status, ...inv, violations });
        console.log(`[ok] ${status} ${url}  (imgs ${inv.images.length}, links ${inv.links.length}, violations ${violations.length})`);

        // Enqueue same-origin child links.
        for (const l of inv.links) {
          const n = normalize(l.href);
          if (n && isHttp(n) && sameOrigin(n) && !seen.has(n) && !/\.(pdf|jpe?g|png|gif|zip|docx?|xlsx?)$/i.test(n)) {
            seen.add(n);
            queue.push(n);
          }
        }
      } catch (e) {
        errors.push({ url, phase: 'goto', error: String(e).slice(0, 200) });
        console.log(`[err] ${url} :: ${String(e).slice(0, 120)}`);
      } finally {
        if (page) { try { await page.close(); } catch { /* already gone */ } }
      }
    }
  } catch (e) {
    // Fatal crawl error (not scoped to a single page). Record it and fall
    // through to report whatever we collected before the failure.
    errors.push({ url: BASE, phase: 'crawl', error: String(e).slice(0, 200) });
    console.error(`[fatal] crawl aborted after ${pages.length} page(s): ${String(e).slice(0, 200)}`);
  } finally {
    if (browser) { try { await browser.close(); } catch { /* already gone */ } }
  }

  await buildReports(pages, errors, queue.length);
}

// ---- report builders -------------------------------------------------------
async function buildReports(pages, errors, remaining) {
  // Inventory JSON
  await writeJSON('inventory.json', { base: BASE, generatedPages: pages.length, remainingInQueue: remaining, pages, errors });

  // A11y JSON (flattened)
  const a11y = pages.map((p) => ({ url: p.url, violations: p.violations }));
  await writeJSON('a11y.json', { base: BASE, pages: a11y, errors });

  // ---- inventory.md
  let md = `# BCA content & asset inventory\n\n`;
  md += `Base: ${BASE}\nPages crawled: ${pages.length}${remaining ? ` (+${remaining} left unqueued at max-pages cap)` : ''}\n\n`;
  for (const p of pages) {
    md += `## ${p.title || '(no title)'}\n`;
    md += `\`${p.url}\` — HTTP ${p.status} — lang=${p.lang || 'MISSING'}\n\n`;
    if (p.metaDescription) md += `Meta description: ${p.metaDescription}\n\n`;

    // Heading hierarchy + skip detection
    md += `**Headings (${p.headings.length})**\n\n`;
    let prev = 0;
    for (const h of p.headings) {
      const skip = prev && h.level > prev + 1 ? ' ⚠️skips level' : '';
      md += `${'  '.repeat(h.level - 1)}- H${h.level}: ${h.text}${skip}\n`;
      prev = h.level;
    }
    const h1s = p.headings.filter((h) => h.level === 1).length;
    if (h1s !== 1) md += `\n> ⚠️ ${h1s} H1 elements (expected exactly 1)\n`;
    md += `\n`;

    // Images
    const badAlt = p.images.filter((i) => !i.hasAltAttr || altLooksAutogenerated(i.alt));
    md += `**Images (${p.images.length}, ${badAlt.length} with missing/auto-generated alt)**\n\n`;
    for (const img of p.images) {
      const flag = !img.hasAltAttr ? '❌ no alt attr'
        : img.alt.trim() === '' ? '⬜ empty alt (decorative?)'
        : altLooksAutogenerated(img.alt) ? '⚠️ auto-generated?'
        : '✅';
      md += `- ${flag} \`${shortSrc(img.src)}\` — alt: ${img.hasAltAttr ? JSON.stringify(img.alt) : '—'}\n`;
    }
    md += `\n`;

    // Embeds
    if (p.iframes.length) {
      md += `**Embeds / iframes (${p.iframes.length})**\n\n`;
      for (const f of p.iframes) md += `- \`${shortSrc(f.src)}\`${f.title ? ` (title: ${f.title})` : ' — ⚠️ no title'}\n`;
      md += `\n`;
    }

    // PDFs & external links
    const pdfs = p.links.filter((l) => /\.pdf($|\?)/i.test(l.href));
    if (pdfs.length) {
      md += `**PDF links (${pdfs.length})**\n\n`;
      for (const l of pdfs) md += `- \`${shortSrc(l.href)}\` — link text: ${JSON.stringify(l.text || l.ariaLabel || '')}${!(l.text || l.ariaLabel) ? ' ⚠️ no accessible name' : ''}\n`;
      md += `\n`;
    }
    const ext = p.links.filter((l) => isHttp(l.href) && !sameOrigin(l.href));
    const extHosts = [...new Set(ext.map((l) => { try { return new URL(l.href).host; } catch { return l.href; } }))];
    if (extHosts.length) md += `**External hosts linked:** ${extHosts.join(', ')}\n\n`;

    // Forms
    if (p.forms.length) {
      md += `**Forms (${p.forms.length})**\n\n`;
      p.forms.forEach((f, i) => {
        const unl = f.controls.filter((c) => !c.labelled);
        md += `- Form ${i + 1} → \`${shortSrc(f.action) || '(no action)'}\` — ${f.controls.length} controls, ${unl.length} unlabeled${unl.length ? ' ⚠️' : ''}\n`;
      });
      md += `\n`;
    }
    md += `---\n\n`;
  }
  await writeText('inventory.md', md);

  // ---- a11y.md
  let am = `# BCA accessibility scan (axe-core, WCAG 2.1 A/AA + best-practice)\n\n`;
  am += `Base: ${BASE} — pages scanned: ${pages.length}\n\n`;
  // Aggregate by rule id
  const byRule = new Map();
  for (const p of pages) {
    for (const v of p.violations) {
      if (!byRule.has(v.id)) byRule.set(v.id, { ...v, pages: new Set(), totalNodes: 0 });
      const agg = byRule.get(v.id);
      agg.pages.add(p.url);
      agg.totalNodes += v.count;
    }
  }
  const impactOrder = { critical: 0, serious: 1, moderate: 2, minor: 3, null: 4, undefined: 4 };
  const rules = [...byRule.values()].sort((a, b) => (impactOrder[a.impact] - impactOrder[b.impact]) || (b.totalNodes - a.totalNodes));
  am += `## Summary — ${rules.length} distinct rules violated\n\n`;
  am += `| Impact | Rule | Instances | Pages | Help |\n|---|---|---:|---:|---|\n`;
  for (const r of rules) {
    am += `| ${r.impact || '—'} | \`${r.id}\` | ${r.totalNodes} | ${r.pages.size} | [${r.help}](${r.helpUrl}) |\n`;
  }
  am += `\n## Per-page detail\n\n`;
  for (const p of pages) {
    am += `### ${p.title || p.url}\n\`${p.url}\` — ${p.violations.length} rules\n\n`;
    if (!p.violations.length) { am += `_No violations detected._\n\n`; continue; }
    for (const v of p.violations.sort((a, b) => impactOrder[a.impact] - impactOrder[b.impact])) {
      am += `- **${v.impact}** \`${v.id}\` — ${v.help} (${v.count} node${v.count === 1 ? '' : 's'})\n`;
      for (const n of v.nodes.slice(0, 3)) am += `    - \`${(n.target || []).join(' ')}\` — \`${(n.html || '').replace(/\n/g, ' ')}\`\n`;
    }
    am += `\n`;
  }
  await writeText('a11y.md', am);

  // ---- summary.md
  const totalImgs = pages.reduce((s, p) => s + p.images.length, 0);
  const badAlt = pages.reduce((s, p) => s + p.images.filter((i) => !i.hasAltAttr || altLooksAutogenerated(i.alt)).length, 0);
  const totalViol = pages.reduce((s, p) => s + p.violations.reduce((a, v) => a + v.count, 0), 0);
  let sm = `# BCA audit summary\n\n`;
  sm += `- Base: ${BASE}\n- Pages crawled: ${pages.length}\n- Total images: ${totalImgs} (⚠️ ${badAlt} missing/auto-generated alt)\n`;
  sm += `- Total axe violation instances: ${totalViol} across ${rules.length} distinct rules\n`;
  sm += `- Crawl errors: ${errors.length}\n\n`;
  sm += `Reports: \`inventory.md\` / \`inventory.json\`, \`a11y.md\` / \`a11y.json\`.\n`;
  if (errors.length) { sm += `\n## Errors\n\n`; for (const e of errors) sm += `- ${e.phase} ${e.url}: ${e.error}\n`; }
  await writeText('summary.md', sm);

  console.log(`\n[done] ${pages.length} pages → ${OUT_DIR}`);
  console.log(`  images ${totalImgs} (bad alt ${badAlt}) | axe instances ${totalViol} | rules ${rules.length} | errors ${errors.length}`);
}

function shortSrc(u) {
  if (!u) return '';
  return u.length > 90 ? u.slice(0, 60) + '…' + u.slice(-25) : u;
}
function writeJSON(name, obj) { return writeFile(path.join(OUT_DIR, name), JSON.stringify(obj, null, 2)); }
function writeText(name, txt) { return writeFile(path.join(OUT_DIR, name), txt); }

main().catch((e) => { console.error(e); process.exit(1); });
